import express from 'express';
import bodyParser from 'body-parser';

const app = express();
app.use(bodyParser.json());

app.post('/api/gemini', (req, res) => {
  const { action } = req.body || {};

  if (action === 'analyze') {
    return res.json({
      skills: [
        { name: 'JavaScript', level: 'Proficient' },
        { name: 'React', level: 'Intermediate' },
        { name: 'Node.js', level: 'Intermediate' }
      ],
      rejectionIntelligence: [
        'No distributed systems experience',
        'Sparse metrics-driven outcomes in bullets'
      ],
      selectionProbability: 42,
      missingSkills: [
        { skill: 'Redis', daysToLearn: 14, roadmap: ['Caching fundamentals', 'Hands-on Redis tutorials'] }
      ]
    });
  }

  if (action === 'improve') {
    return res.json({
      boostedProbability: 89,
      improvedResume: 'Sample improved resume text generated by mock server.',
      coverLetter: 'Sample cover letter generated by mock server.'
    });
  }

  if (action === 'interview') {
    return res.json({ question: 'Describe a time you shipped a critical feature.', context: 'We are assessing ownership and trade-offs.' });
  }

  if (action === 'evaluate') {
    return res.json({ feedback: 'Good answer; be more specific about metrics.', score: 78, improvedAnswer: 'Improved answer version...' });
  }

  if (action === 'strategy') {
    return res.json({ plan: [ { day: 1, priority: 'High', task: 'Polish resume bullets' }, { day: 7, priority: 'Medium', task: 'Build small demo project' } ] });
  }

  res.status(400).json({ error: 'Unknown action' });
});

const port = 4000;
app.listen(port, () => console.log(`Mock Gemini API listening on http://localhost:${port}`));
